### ISSUE TITLE
Handling large numbers (400) of locations?

### ISSUE THREAD

**Issue by Herteby** [mapbox/node-or-tools#20]
We have around 400 missions/locations. From what I understand, that means we need to start with 400x400 distance matrix. Both yours and Google's Distance Matrix APIs have a maximum of 25x25.
Is it expected that I make many (about 256) requests, and then merge the matrixes myself?
And if the Distance Matrix API can only handle 25x25, is OR-Tools even built to handle this many locations? Or am I supposed to do some sort of pre-culling before creating the matrix?

**Comment by daniel-j-h** [comment]
Making smaller requests and them re-assembling them on the fly is what I can recommend, yes. There's also the option to run a full routing engine locally (e.g. see [osrm](https://github.com/Project-OSRM/osrm-backend#open-source-routing-machine)) where you don't have any limits. Not sure if it's worth the hassle - just make small chunked requests.

400x400 should work just fine with the node-or-tools Node.js bindings.
Keep in mind the solutions will be of heuristical nature.

**Comment by Herteby** [comment]
Ah, good to hear! I was just a bit worried because neither your or Google's guides said anything about wether it was common practice to make multiple requests and merge them.
