### ISSUE TITLE
The routes result is empty

### ISSUE THREAD

**Issue by Nacabacu** [mapbox/node-or-tools#42]
Hi, @daniel-j-h.
I have tried this library with these params.
numNodes = 7 (except depot)
demands = all 1
numVehicles = 3
and if I use vehicleCapacity >= 5 it will return just 2 routes and another empty route with cost 8778.
If I use vehicleCapacity = 4 it will return 3 routes with cost 9892.
How can I set the results to have full routes?
Thank you for your response.
ps. sry for my Eng, hope you understand.

**Comment by daniel-j-h** [comment]
I think what you're looking for is:
- https://github.com/mapbox/node-or-tools/issues/5
- https://github.com/mapbox/node-or-tools/issues/1

**Comment by Nacabacu** [comment]
Thank you so much.
