### ISSUE TITLE
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' on RHEL 7.4 

### ISSUE THREAD

**Issue by ivosabev** [mapbox/node-or-tools#43]
The system supports only up to GLIBCXX_3.4.19. Any ideas on how to make it work?

The highest possible installed version is: `libstdc++.i686                4.8.5-16.el7`

I

**Comment by daniel-j-h** [comment]
Please see https://github.com/mapbox/node-or-tools#quick-start:

We ship pre-built native binaries (for Node.js LTS 4 and 6 on Linux and macOS). You will need a compatible C++ stdlib, see below if you encounter issues. Building from source is supported via the `--build-from-source` flag.

If you can't use mason for dependencies you have to install them on your own:

https://github.com/mapbox/node-or-tools/blob/master/scripts/install-deps.sh

**Comment by ivosabev** [comment]
Made it work by compiling on the server. Thanks!

**Comment by daniel-j-h** [comment]
Great, happy routing! 🚗 ✨
