### ISSUE TITLE
node_or_tools@1.0.6 and node@11.4.0

### ISSUE THREAD

**Issue by pabx06** [mapbox/node-or-tools#72]
any plan for supporting recent node version ?
```
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/node_or_tools/v1.0.6/Release/node-v67-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for node_or_tools@1.0.6 and node@11.4.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Pre-built binaries not installable for node_or_tools@1.0.6 and node@11.4.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Connection closed while downloading tarball file 
```

**Comment by coderroggie** [comment]
@pabx06 try using:

```
  "node_or_tools": "git+https://github.com/mapbox/node-or-tools.git#v1.0.7",
```
in your package.json file.

@danpaz Any way we can get 1.0.7 published to the npm repo?  I'm no expert at the travis ci process, but it looks like one of the versions was uploaded... not sure why that script executes 6 times (from appearances...)

**Comment by danpaz** [comment]
@coderroggie The binary is on s3 but the npm package isn't updated on the npm registry. I am working with npm on getting permission to publish the package, it has to be done by the package owner or a collaborator. I'll report back here when that's done.

**Comment by coderroggie** [comment]
@danpaz how goes the battle?

**Comment by xiaogu-space** [comment]
@danpaz how goes the battle?

**Comment by danpaz** [comment]
@coderroggie @xiaogu-space @pabx06 1.0.7 is now [published to npm](https://www.npmjs.com/package/node_or_tools/v/1.0.7). Thanks for your patience!

**Comment by coderroggie** [comment]
@danpaz thanks!
